### ISSUE TITLE
Advices

### ISSUE THREAD

**Issue by davidp88** [crittermike/shortkeys#416]
1.Think completely and work and that thinking should be done at once,as little thinking causes mistakes.

2.If u add a new feature or update an existing feature think of all the ways of how it can be improved

3.Increase patience

4.Avoid laziness in work

5.Do important work first

6.If u can't repro a bug normally then test it thoroughly and try to repro for 2-3 times.

7.As far as possible try to repro bugs in win10 bcoz most of the users in the world are using w10

Make these tips read by ur dev's, it's important,bcoz if they completely think and work then even bugs will be properly fixed.

**Comment by wsmwk** [comment]
@crittermike this doesn't seem to be an actionable report.  perhaps even spam, like https://github.com/Bill13579/tabby/issues/77 ?
