### ISSUE TITLE
Can't remove the Ctrl+W shortcut

### ISSUE THREAD

**Issue by EpicBrains** [crittermike/shortkeys#497]
I cant remove it with the "Do Nothing" nor change it to something else. 

PS: I can change it in the Shortkeys Options but it wont do anything.

**Comment by piotr-dobrogost** [comment]
Why did you close this?

**Comment by oscarsun72** [comment]
> Why did you close this?

Last few days I first time to use  Selenium in C# to control Chrome ,howerver  if i keyed down Ctrl  + w close the Chrome tab or windows, it would throw a exception , thenI think it will be a good idea if I could let the combination keys invalid …… 感恩感恩　南無阿彌陀佛

**Comment by EpicBrains** [comment]
> Why did you close this?

Because I figured it out long long ago and the issue was forgotten.

**Comment by piotr-dobrogost** [comment]
> Because I figured it out long long ago and the issue was forgotten.

What have you figured out?
