### ISSUE TITLE
Feature Request: Move to beginning / end of the line

### ISSUE THREAD

**Issue by random-un** [crittermike/shortkeys#498]
* Context
  * In Chrome OS, there are [keyboard shortcuts that move the cursor while text editing](https://support.google.com/chromebook/answer/183101?hl=en). These include:
    * **Move to beginning of the line**: Search  + Left arrow
    * **Move to end of the line**: Search  + Right arrow 
  * I use these shortcuts on small keyboards that do not have dedicated `Home` and `End` buttons

* Feature Request
  * Introduce a ShortKeys feature that lets user assign the above commands to a keyboard shortcut via the browser's "Keyboard Shortcuts" settings for ShortKeys.

* Added thoughts
  * I suspect Chrome may not give extensions access to this functionality, but thought I'd ask anyway!
  * I am so grateful for the wonderful ShortKeys extension -- thank you so much for creating such an incredible tool!

**Comment by Tweoss** [comment]
Hi @random-un,
If you still happen to have a need for this shortcut, the following js snippets should work in a normal textarea. This may be preferred over adding a shortcut specifically for moving to the end of the line.
```
// move to end 
document.activeElement.selectionStart = document.activeElement.selectionEnd = document.activeElement.value.indexOf('\n', document.activeElement.selectionStart)
// move to start
document.activeElement.selectionStart = document.activeElement.selectionEnd = document.activeElement.value.lastIndexOf('\n', document.activeElement.selectionStart - 1) + 1
```

**Comment by random-un** [comment]
Cool idea! I've used Shortkeys for years and only utilize the [Chrome-level extension keyboard shortcuts](chrome://extensions/shortcuts), but this approach seems to work great in many pages. Will continue to experiment!

Screenshot of this solution --
![image](https://user-images.githubusercontent.com/35006176/192953341-3bf01bc2-9a47-434a-a47b-f5c9b94b587b.png)
