### ISSUE TITLE
error th Requiring Trusted Types

### ISSUE THREAD

**Issue by vpineda7** [crittermike/shortkeys#639]
I want to report a issue with chrome version 127.0.6533.120 and I got this error in console log: 
_Uncaught TypeError: Failed to set the 'textContent' property on 'Node': This document requires 'TrustedScript' assignment._

I found that this occurs because it is related to a new restrinction: 
_Your site tries to use a plain string in a DOM modification where a Trusted Type is expected. Requiring Trusted Types for DOM modifications helps to prevent cross-site scripting attacks._

Please take in count that is required to change the way to inject the js script s

**Comment by crittermike** [comment]
See #621
